ROOT_PATH = '/home/algorithm/Music/MusicGeneration_VAE/'
DATA_PATH = ROOT_PATH + 'data'
PHRASE_DATA_PATH = DATA_PATH + 'phrase_data'
BAR_DATA_PATH = DATA_PATH + 'bar_data'

BOARD_PATH = ROOT_PATH + 'board'
MODEL_SAVE_PATH = ROOT_PATH + 'model'

PHRASE_MODEL_NUMBER = 0

PITCH_SIZE = 96
BAR_SIZE = 96
BAR_CNT_IN_PHRASE = 4

TRAIN_EPOCH = 10000
BATCH_CNT = 10

FEATURE_DIM = 510
